baseURL = ""

title = "Bryan Johnston"

theme = "HDB-hugo-theme"

[params]

  # Author of the site, will be used in meta information
  author = ""

  # Description of the site, will be used in meta information
  description = ""

  # Name of home page
  landingPageName = ""

  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css = ["css/custom-override-theme-bryan.css"]

  # Change the title separator. Default to "::".
  titleSeparator = "::"

  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = true

  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"

  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton = false

  # Disable search function. It will hide search bar
  disableSearch = false

  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false

  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false

  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false

  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false

  # If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
  disableMermaid = false

  # Specifies the remote location of the mermaid js
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"

  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON"]


